language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN'
script:
  - npm set https://registry.npmjs.org/:_authToken=$NPM_TOKEN
  - npm install
  - npm run build
  - npm publish
