sudo: false
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
env:
  global:
    secure: "SaNP1qwy93dq3xUFzV+WhLu6L1kOQPHrkEzpDpwwZQFf0exgWdN0VTaB+8Y4c3aIMciH3/vJwLBZ2OcKjS38yYmgxMdww/C3CCiCaGgcYbw9vz6qAX1XsM/RRh2U+55aDinYHb+9d7S71C0pfpeJNNrtG7p2I7FxQnnKaxt8EOWeHYx2EJSpP3KD4dy9a/wmRugIxWxhqKsrMBxfovzjC09FbvasTin3EqGSr/3zu5IhkPW7lRfjdOEuvhCp3H49+vwIMeYl+4oas9JyNfqFM28ErNB3hXMJ9yfRb3/pRE/FuM192E4pCX6Hpmch6cg6ZVqq7ENp3AsHp3XB8owEzndOSENoYXp6tOFivRezXsadsTrfmwejCY3u6GF36axuV6yI8Onp9uWDZLAUOVZxMVFpbEXF6Yio2cF13BiVFdUTYVNYMpK/88M/FHZgqxgB7GMU7fJHRTLFwMf5QLf1Wlx+fJyGoTVVOqNGyEHIlDZ1tEH4G3v9CnExDKtBlpOXVdKGlbf862yH0colpKJ4o3wlSRFnaJ/wBSf1UBIxQa5mjp3RO3euUKkft1+2RBc05c9wpO/Q7WaBaQDspMTNDqg7+Z36KJeu25PAM3wFfXZP9/DmUEaM3yNGy9EGSHaYku1LYPxf/X14LarTbd5U8gcmdWMqrHd/ddqgblGZtrU="
branches:
  only:
    - master
deploy:
  provider: npm
script:
  - npm install
  - npm run build
#  - npm run deploy
