language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: "maheshmore4321@gmail.com"
  api_key: $NPM_TOKEN
script:
  - npm login
  - npm run build
  - npm publish
